In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
path = "/content/drive/MyDrive/Colab Notebooks/E-Commerce Customer Intelligence & Sales Analytics/Online Retail Data Set.xlsx"
df = pd.read_excel(path)

In [ ]:
print(df.shape)
df.head()

(541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [ ]:
df[df['CustomerID'].isnull()].shape             #Missing CustomerID

(135080, 8)

In [ ]:
df[df['CustomerID'].isnull()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom

In [ ]:
df[df['Description'].isnull()].shape               #Missing discription

(1454, 8)

In [ ]:
df[df['Quantity'] <= 0].shape                        #Quantity ≤ 0

(10624, 8)

In [ ]:
df[df['InvoiceNo'].astype(str).str.startswith('C')].shape                 # Cancelled Invoices (C...)

(9288, 8)

In [ ]:
df[df['UnitPrice'] <= 0].shape                      # UnitPrice ≤ 0

(2517, 8)

In [ ]:
df = df.dropna(subset=['CustomerID'])                   #Removing rows with missing Description

In [ ]:
df = df.dropna(subset=['Description'])                  #Removing rows with missing Description

In [ ]:
df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]         # Remove cancelled invoices

In [ ]:
df = df[df['Quantity'] > 0]                      # Remove Quantity ≤ 0

In [ ]:
df = df[df['UnitPrice'] > 0]                      # Remove UnitPrice ≤ 0

In [ ]:
print(df.shape)

(397884, 8)

In [ ]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [ ]:
df['Revenue'] = df['Quantity'] * df['UnitPrice']
df[['Quantity','UnitPrice','Revenue']].head()

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

In [42]:
df.to_csv(
    "/content/drive/MyDrive/Colab Notebooks/E-Commerce Customer Intelligence & Sales Analytics/cleaned_retail.csv",
    index=False
)