In [3]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/Colab Notebooks/E-Commerce Customer Intelligence & Sales Analytics/data/cleaned_retail.csv",
    parse_dates=['InvoiceDate']
)

In [4]:
df.shape

(397884, 9)

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [8]:
df[['Quantity','UnitPrice','Revenue']].head()

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

In [9]:
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['MonthName'] = df['InvoiceDate'].dt.month_name()
df['Day'] = df['InvoiceDate'].dt.day
df['Hour'] = df['InvoiceDate'].dt.hour
df['Weekday'] = df['InvoiceDate'].dt.day_name()

In [10]:
df[['InvoiceDate','Year','MonthName','Weekday','Hour']].head()

          InvoiceDate  Year MonthName    Weekday  Hour
0 2010-12-01 08:26:00  2010  December  Wednesday     8
1 2010-12-01 08:26:00  2010  December  Wednesday     8
2 2010-12-01 08:26:00  2010  December  Wednesday     8
3 2010-12-01 08:26:00  2010  December  Wednesday     8
4 2010-12-01 08:26:00  2010  December  Wednesday     8

In [11]:
order_revenue = (
    df.groupby('InvoiceNo')['Revenue']
      .sum()
      .reset_index()
)

order_revenue.head()

   InvoiceNo  Revenue
0     536365   139.12
1     536366    22.20
2     536367   278.73
3     536368    70.05
4     536369    17.85

In [13]:
df.to_csv(
    "/content/drive/MyDrive/Colab Notebooks/E-Commerce Customer Intelligence & Sales Analytics/data/retail_features.csv",
    index=False
)